# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [7]:
import numpy as np


#### 2. Print the numpy version and the configuration  (★☆☆)

In [4]:
print(np.__version__)

1.18.2


#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
a=np.zeros(10)  #zeros and not zeroes
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [10]:
mem_size=a.size*a.itemsize
print(mem_size)

80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [16]:
print(a[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
arr=np.arange(0,9)
arr=arr.reshape((3,3))
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [20]:
given=[1,2,0,0,4,0]
for i in given:
    if i!=0:
        print(given.index(i))
  # OR
# nz = np.nonzero([1,2,0,0,4,0])
# print(nz)

0
1
4


#### 11. Create a 3x3 identity matrix (★☆☆)

In [32]:
# mat=np.identity(3)
# print(mat)

print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [37]:
#arr=np.array([(1,2,3),(3,4,5),(6,7,8)])
#print(arr)
print(np.random.random((3,3,3))) # 3 matrix of 3*3 shape of any random values

[[[0.69926275 0.53445022 0.98026773]
  [0.97416653 0.07807115 0.29515378]
  [0.49874019 0.95032726 0.31247402]]

 [[0.96434408 0.56325371 0.98825922]
  [0.47147379 0.42796047 0.91992074]
  [0.63339724 0.87689928 0.65234479]]

 [[0.28377331 0.32735055 0.1014939 ]
  [0.13916338 0.61560976 0.75088126]
  [0.65791363 0.09411543 0.16825974]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [47]:

a=np.random.randint(0,100000,(10,10)) #for random()start end not req....but necessary for randint()
print(a)
print("Maximum is",a.max())
m= a.min()

print(f"minimum is{m}")

[[82091 96932 86636 17535 85238 28336 15409 19495 42984 56178]
 [61156 87249 28634 69857 55843 18429 28891 61831 28376 54265]
 [94595 13334 98483 72159 65293 33640 44919 81259 26081 49700]
 [52504 34700 61527 23703 26667 46955 74373 20656 32645 90005]
 [ 9101 21086 10882 82949  7203 70073 39185 99373 50830 79114]
 [95079 91043 50185 16168 48985 93316   294 96913 24914 77987]
 [25409 70659  8992 69662 64502 18121 77422 14293 76578 63118]
 [39523 68264 17868 60971 72386 31677 55703 51089 55856 77748]
 [51336 79904 67850 45159 35791 22824  1925 82660 74807 94604]
 [96265 82156 55999 24568  5811 20131 21408  3389 74057 54696]]
Maximum is 99373
minimum is294


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [51]:
arr=np.random.randint(0,100,30)  # (start,end,size) for 1d ,else for size us tuple (3,2) 
print(arr.mean())

44.86666666666667


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [55]:
#a=np.zeros((3,3))  # use double bracket because arguments passed are 2 so as a tuple


Z = np.ones((10,10))

Z[1:-1,1:-1] = 0

print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [59]:
a=np.ones((5,5))
a=np.pad(a,pad_width=1,mode="constant",constant_values=0) ''' (operate on which array,how much to pad,  ,  )'''

print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [69]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [12]:
#a=np.ones((5,5))
import numpy as np
a=np.diag(1+np.arange(4),k=-1) # diag(the array to put,int that represents the diagonal...)
''' 0=diag
1=upper to diag
-1= lower to diag''' 
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [70]:
a=np.zeros((8,8))
a[0:8:2,0:8:2]=1
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
print(np.unravel_index(100,(6,7,8))) #(noth of the element ,(size of the array))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [74]:
a=np.array([(1,0),(0,1)])
a=np.tile(a,(4,4))
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [75]:
Z = np.random.random((5,5))

Zmax, Zmin = Z.max(), Z.min()

Z = (Z - Zmin)/(Zmax - Zmin)

print(Z)

[[0.21556341 0.75921228 0.80709005 0.357544   0.19485431]
 [0.24799206 0.36244912 0.40290255 1.         0.5865145 ]
 [0.86425361 0.57519242 0.30564159 0.79898564 0.45245866]
 [0.         0.10615701 0.91985291 0.46588474 0.83814216]
 [0.12731022 0.31995566 0.92489828 0.51131003 0.13324664]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),

("g", np.ubyte, 1),

("b", np.ubyte, 1),

("a", np.ubyte, 1)])



#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [82]:
a=np.random.randint(0,1000,(5,3))     
b=np.random.randint(0,1000,(3,2))
''' 
  1)      c=np.zeros((5,2))                    
        for i in range(len(a)):
            for p in range(len(b[0])):
                for k in range(len(b)):

                    c[i][p]=a[i][k]*b[k][p]
        print("multiplication is\n") 
        print(c)
'''
# 2)   print(a," * ",b," = ",a@b)

print(np.dot(a,b))


[[ 660291  593837]
 [ 980436  627991]
 [ 725772  431741]
 [1000551 1036147]
 [ 643557  421410]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [15]:
import numpy as np
a=np.random.randint(0,21,(1,15))

'''
ERROR
c=[3,4,5,6,7,8]
for i in range(len(a)):
    if a[i] in c:
        a[i]=-a[i]
        
print(a)        
     '''   

a[(3<a) and (a<=8)]*=-1

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z**z
1j*Z
Z/1/1

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
0
array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Z = np.random.uniform(-10,+10,10)

print (np.copysign(np.ceil(np.abs(Z)), Z))

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
print(np.intersect1d(array1,array2))

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [16]:
defaults = np.seterr(all="ignore")

Z = np.ones(1) / 0

_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [24]:
import numpy as np
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
today=np.datetime64('today','D')
tom=np.datetime64('today','D')+np.timedelta64(1,'D')

print("yesterday's date : ",yesterday)
print("today's date : ",today)
print("tomorrow's date : ",tom)


yesterday's date :  2020-04-01
today's date :  2020-04-02
tomorrow's date :  2020-04-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [25]:
print(np.arange('2016-07','2016-08',dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [33]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)

print (np.floor(Z))

print (np.ceil(Z)-1)

print (Z.astype(int))

print (np.trunc(Z))

[3. 0. 1. 0. 0. 2. 6. 7. 6. 9.]
[3. 0. 1. 0. 0. 2. 6. 7. 6. 9.]
[3. 0. 1. 0. 0. 2. 6. 7. 6. 9.]
[3 0 1 0 0 2 6 7 6 9]
[3. 0. 1. 0. 0. 2. 6. 7. 6. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [39]:
a=np.random.randint(0,5,(5,5))
print(a)

z=np.zeros((5,5))
z[::,0]=1
for i in range(1,5):
    z[::,i]=1+z[::,i-1]
    
print(z)    


[[0 3 4 4 4]
 [1 3 4 2 0]
 [1 3 2 0 3]
 [4 3 2 2 0]
 [3 2 2 0 3]]
[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [40]:
def generate():

for x in range(10):

yield x

Z = np.fromiter(generate(),dtype=float,count=-1)

print(Z)



TypeError: fromiter() missing required argument 'dtype' (pos 2)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [43]:
a = np.linspace(0,1,12,endpoint=True)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [50]:
Z = np.random.random(10)

Z.sort()

print(Z)

[0.10094659 0.16517835 0.17687569 0.1794564  0.18322183 0.22940576
 0.6937365  0.87964679 0.93321284 0.9679864 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [51]:
a=np.random.random(10)
b=np.random.random(10)

value=np.array_equal(a,b)
print(value)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [52]:
a.flags.writeable=False
a[0]=1


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [62]:
'''c=np.random.random((10,2))

import math
for i in range(10):
    a=c[i][0]
    b=c[i][1]
    s=a**2
    s+=b**2
    a1=math.sqrt(s)
    b1=math.atan(b/a)
    b1=math.degrees(b1)
    c[i]=[a1,b1]
    
print(c)'''

Z = np.random.random((10,2))

X,Y = Z[:,0], Z[:,1]

R = np.sqrt(X**2+Y**2)

T = np.arctan2(Y,X)

print(R)

print(T)

[0.96551163 0.74739988 0.29742249 0.87472783 0.35352176 0.5854272
 0.69616993 0.9438117  1.17855924 0.52267724]
[1.35939678 0.87662989 0.21609137 1.44091651 1.42745709 0.40905822
 0.47684332 1.0830959  0.79735916 1.41064189]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [64]:
Z = np.random.random(10)

Z[Z.argmax()] = 0

print(Z)

[0.90331621 0.         0.33809925 0.56121722 0.56186721 0.13563815
 0.74627125 0.49103821 0.58221619 0.46971409]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [67]:
Z = np.arange(100)

v = np.random.uniform(0,100)

index = (np.abs(Z-v)).argmin()

print(Z[index])

51


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)